# Este é um fluxo de trabalho básico para ajudá-lo a começar com Actions

name: teste

# Controla quando a ação será executada.
on:
  # Aciona o fluxo de trabalho em eventos de push ou pull request, mas somente para o branch principal
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite que você execute esse fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único job chamado "build"
  API-Tests-Postman-Collection:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest
    
    # permite públicar o report de testes no GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://jvluzc.github.io/ronbugado-academy12.2-api-postman/report.html

    # As etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Faz o checkout do repositório no Git Hub, para que o job possa acessá-lo
      - uses: actions/checkout@v3

      
      - name: Etapa 1 - Verificar versão do Newman e do Node
        run: |
          newman --version
          node --version
          
      
      - name: Etapa 2 - Instalar Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      
      - name: Etapa 3 - Executar Coleção do Postman
        run: newman run ./ronbugado-collecition-ci.json -e ./ronbugado-environments-ci.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/report.html
   
      # Executa um conjunto de comandos usando o shell do runner
      - name: Etapa 4 - Arquivar Resultado da Execução dos Testes
        uses: actions/upload-artifact@v4  # Atualizado para a versão v3
        with:
          name: report
          path: ./results/report.html

      # Publica o report de testes no GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/
          
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        