# Este é um fluxo de trabalho básico para ajudá-lo a começar com Actions

nome: Pipiline Ron Bugado Postman

# Controla quando a ação será executada.
on:
  # Aciona o fluxo de trabalho em eventos de push ou pull request, mas somente para o branch principal
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite que você execute esse fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único job chamado "build"
  build:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Faz o checkout do seu repositório em $GITHUB_WORKSPACE, para que seu job possa acessá-lo
      - uses: actions/checkout@v2

      # Executa um conjunto de comandos usando o shell do runner
      - name: Verificar versão do Newman e do Node
        run: |
          newman --version
          node --version
          
      # Executa um único comando usando o shell do runner
      - name: Instalar Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      # Executa um conjunto de comandos usando o shell do runner
      - name: Executar coleção
        run: newman run ./ronbugado-collecition-ci.json -e ./ronbugado-environments-ci.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
   
      # Executa um conjunto de comandos usando o shell do runner
      - name: Arquivar artefatos de produção
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html
