name: Pipeline-PostmanAPI-RonBugado

# Define quando a ação será executada
on:
  # Dispara a execução do workflow nos eventos de push ou pull request apenas para o branch principal
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Permite executar o workflow manualmente a partir da aba Actions
  workflow_dispatch:

# Um workflow é composto por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este workflow contém um único job chamado "build"
  build:
    # O tipo de runner que o job vai executar
    runs-on: ubuntu-latest

    # Etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v2

      # Verifica as versões do Newman e Node
      - name: Passo 1: Verificar versão do Newman e Node
        run: |
          newman --version
          node --version
          
      # Instala o Newman Reporter HTMLEXTRA
      - name: Passo 2: Instalar o Newman-Reporter-HTMLEXTRA
        run: sudo npm install -g newman-reporter-htmlextra
        
      # Executa a coleção Postman utilizando o Newman e gera o relatório
      - name: Passo 3: Executar a coleção
        run: newman run ./ronbugado-ci.json -e ./ronbugado-envi.json --reporters cli,-r htmlextra --reporter-htmlextra-export ./results/Report.html
     
      # Arquiva os artefatos de produção (relatório gerado)
      - name: Passo 4: Arquivar artefatos de produção
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
            name: report
            path: ./results/Report.html
