# Este é um fluxo de trabalho básico para ajudá-lo a começar com Actions

name: teste

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  API-Tests-Postman-Collection:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://Rapha3la.github.io/ron-bugado-academy12.2-api-postman/report.html

    steps:
      - name: Etapa 1 - Clonar Repositório do Projeto para a Máquina Virtual do GitHub Actions
        uses: actions/checkout@v4
      
      - name: Etapa 2 - Verificar versão do Newman e do Node
        run: |
          newman --version
          node --version
          
      - name: Etapa 3 - Instalar Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      - name: Etapa 4 - Executar Coleção do Postman
        run: newman run ./ronbugado-collecition-ci.json -e ./ronbugado-environments-ci.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/report.html
   
      # Publica o report de testes no GitHub Pages
      - name: Etapa 5 - Configurar GitHub Pages para Hospedagem dos Relatórios
        uses: actions/configure-pages@v5

      - name: Etapa 6 - Fazer Upload dos Relatórios Gerados
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: results/
          
      - name: Etapa 7 - Publicar Relatórios de Testes no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
